# Generated by Django 4.2.5 on 2023-11-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachesCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineApp.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineApp.teacher')),
            ],
        ),
    ]
