# Generated by Django 4.2.5 on 2023-11-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0002_teachescourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakesCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineApp.student')),
            ],
        ),
    ]
